name: XML Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'module/immerse_rules.xml'
      - 'module/immerse_rules.xsd'
  pull_request:
    branches: [ main ]
    paths:
      - 'module/immerse_rules.xml'
      - 'module/immerse_rules.xsd'

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install libxml2-utils
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      
    - name: Validate XML files
      run: |
        XML_FILE="module/immerse_rules.xml"
        XSD_FILE="module/immerse_rules.xsd"

        if [ ! -f "$XSD_FILE" ]; then
          echo "XSD schema file not found!"
          exit 1
        fi

        echo "Validating $XML_FILE against $XSD_FILE..."

        output=$(xmllint --schema "$XSD_FILE" --noout "$XML_FILE" 2>&1)
        xmllint_exit=$?

        echo "$output" | while read line; do
          if [[ "$line" =~ ^($XML_FILE:([0-9]+):) ]]; then
            prefix=${BASH_REMATCH[1]}
            echo -e "\033[1;31mLine ${BASH_REMATCH[2]}:\033[0m ${line#"$prefix"}"
          else
            echo "$line"
          fi
        done

        if [ $xmllint_exit -ne 0 ]; then
          exit 1
        fi


