name: XML Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'module/immerse_rules.xml'
      - 'module/immerse_rules.xsd'
  pull_request:
    branches: [ main ]
    paths:
      - 'module/immerse_rules.xml'
      - 'module/immerse_rules.xsd'

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install libxml2-utils
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      
    - name: Validate XML files
      run: |
        if [ -f "module/immerse_rules.xsd" ]; then
          echo "Validating XML against XSD schema..."
          xmllint --schema module/immerse_rules.xsd --noout module/immerse_rules.xml
        else
          echo "XSD schema file not found!"
          exit 1
        fi
