name: Zip and Release

on:
  push:
    branches:
      - main
    paths:
      - 'module/**'
  workflow_dispatch:
    inputs:
      version:
        description: '指定版本号（留空为RunID）'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update module version
        id: update_version
        run: |
          FILE=module/module.prop

          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(date +'%Y%m%d%H%M')
          fi

          VERSION_CODE=${{ github.run_number }}

          sed -i "s/^version=.*/version=$VERSION/" $FILE
          sed -i "s/^versionCode=.*/versionCode=$VERSION_CODE/" $FILE

          echo "module_version=$VERSION" >> $GITHUB_OUTPUT
          echo "module_versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Run sorting script
        run: |
          python3 -m pip install --user --upgrade pip || true
          python3 scripts/sort_release_files.py module/immerse_rules.xml list.csv || true
          if ! git diff --quiet; then
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add module/immerse_rules.xml list.csv || true
            git commit -m "chore: sort immerse_rules.xml and list.csv before release [skip ci]" || echo "No changes to commit"
            git push || echo "Push failed"
          else
            echo "No sorting changes"
          fi

      - name: Create zip file
        run: |
          cd module
          zip -r ../MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}.zip . -x "*/immerse_rules.xsd" "immerse_rules.xsd"

      - name: Update "update.json" in gh-pages
        run: |
          # 切到 gh-pages 分支（不存在则新建）
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages

          # 保证分支只保留 update.json
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

          ZIP_NAME="MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}.zip"

          cat <<EOF > update.json
          {
            "version": "${{ steps.update_version.outputs.module_version }}",
            "versionCode": ${{ steps.update_version.outputs.module_versionCode }},
            "zipUrl": "https://github.com/${{ github.repository }}/releases/download/AutoBuild_${{ steps.update_version.outputs.module_version }}/$ZIP_NAME",
            "changelog": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/changelog.md"
          }
          EOF

          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add update.json
          git commit -m "Update update.json for version ${{ steps.update_version.outputs.module_version }}_${{ steps.update_version.outputs.module_versionCode }}" || echo "No changes"
          git push origin gh-pages --force

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}
          tag_name: AutoBuild_${{ steps.update_version.outputs.module_version }}
          files: MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Post to Telegram Channel
        env:
          GROUP_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ZIP_FILE: "MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}.zip"
        
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            COMMIT_MESSAGE="Manually run by ${{ github.actor }}"
          else
            RAW_MSG="${{ github.event.head_commit.message }}"
            TRIMMED_MSG=$(echo "$RAW_MSG" | sed -e '1{/^$/d}' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            COMMIT_MESSAGE="New push to GitHub
            <pre>$TRIMMED_MSG</pre>
            by <code>${{ github.event.head_commit.author.name }}</code>  
            See commit detail <a href='${{ github.event.head_commit.url }}'>here</a>"
          fi

          cd ${{ github.workspace }}
          curl -F chat_id=${GROUP_ID} \
               -F document=@"${ZIP_FILE}" \
               -F parse_mode="HTML" \
               -F caption="$COMMIT_MESSAGE" \
               https://api.telegram.org/bot${BOT_TOKEN}/sendDocument
