name: Zip and Release

on:
  push:
    branches:
      - main
    paths:
      - 'module/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set timestamp
        id: timestamp
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "datetime=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "datetime=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          fi

      - name: Create zip file
        run: |
          cd module
          zip -r ../MiNavBarImmerse_${{ steps.timestamp.outputs.datetime }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MiNavBarImmerse_${{ steps.timestamp.outputs.datetime }}
          tag: AutoBuild
          files: MiNavBarImmerse_${{ steps.timestamp.outputs.datetime }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
