name: Zip and Release

on:
  push:
    branches:
      - main
    paths:
      - 'module/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (YYYYMMDD, optional, will override automatic date)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update module version
        id: update_version
        run: |
          FILE=module/module.prop

          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(date +'%Y%m%d')

          VERSION_CODE=$(date +'%Y%m%d%H%M')

          sed -i "s/^version=.*/version=$VERSION/" $FILE
          sed -i "s/^versionCode=.*/versionCode=$VERSION_CODE/" $FILE

          echo "module_version=$VERSION" >> $GITHUB_OUTPUT
          echo "module_versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Create zip file
        run: |
          cd module
          zip -r ../MiNavBarImmerse_${{ steps.update_version.outputs.module_versionCode }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}
          tag_name: AutoBuild_${{ steps.update_version.outputs.module_versionCode }}
          files: MiNavBarImmerse_${{ steps.update_version.outputs.module_versionCode }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
