name: Zip and Release

on:
  push:
    branches:
      - main
    paths:
      - 'module/**'
  workflow_dispatch:
    inputs:
      test_release:
        description: '是否测试 release 步骤'
        required: false
        default: 'true'

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip file (timestamped)
        run: |
          TIMESTAMP=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M%S')
          ZIP_NAME="MiNavBarImmerse_${TIMESTAMP}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          cd module
          zip -r ../"$ZIP_NAME" .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: ${{ env.ZIP_NAME }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "New version：${{ env.ZIP_NAME }}"
