name: Zip and Release

on:
  push:
    branches:
      - main
    paths:
      - 'module/**'
  workflow_dispatch:
    inputs:
      version:
        description: '指定版本号'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update module version
        id: update_version
        run: |
          FILE=module/module.prop

          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(date +'%Y%m%d')
          fi

          VERSION_CODE=${{ github.run_number }}

          sed -i "s/^version=.*/version=$VERSION/" $FILE
          sed -i "s/^versionCode=.*/versionCode=$VERSION_CODE/" $FILE

          echo "module_version=$VERSION" >> $GITHUB_OUTPUT
          echo "module_versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Create zip file
        run: |
          cd module
          zip -r ../MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}.zip .

      - name: Update "Update.json"
        run: |
          ZIP_NAME="MiNavBarImmerse_${{ steps.update_version.outputs.module_versionCode }}.zip"
          cat <<EOF > Update.json
          {
            "version": "${{ steps.update_version.outputs.module_version }}",
            "versionCode": ${{ steps.update_version.outputs.module_versionCode }},
            "zipUrl": "https://github.com/${{ github.repository }}/releases/download/AutoBuild_${{ steps.update_version.outputs.module_version }}/$ZIP_NAME",
            "changelog": "$LAST_COMMIT"
          }
          EOF

      - name: Update.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -f Update.json
          git commit -m "Version ${{ steps.update_version.outputs.module_versionCode }}" || echo "No changes"
          git push

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}
          tag_name: AutoBuild_${{ steps.update_version.outputs.module_version }}
          files: MiNavBarImmerse_${{ steps.update_version.outputs.module_version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
